import React from "react";

export default function Policies() {
  return (
    <div className="py-10 px-20 w-[75%]">
      <h1 className="text-3xl font-medium pb-8">
        Manago Manpower - Privacy Policy
      </h1>
      <p className="pb-4">Last updated: 8th July 2024</p>
      <p className="pb-4">
        This Privacy Policy describes how Manago Manpower Solutions ("Manago",
        "we", "our", or "us") collects, uses, and discloses your information
        when you visit our website https://manago.in (the "Service") and
        explains your privacy rights and protections under the law.
      </p>
      <h2 className="text-3xl font-medium pb-4">About Us</h2>
      <p className="pb-4">
        Manago Manpower Solutions ("Manago") is designed as an end-to-end
        solution for all Food & Beverages Industry needs. We provide services
        like Manpower Solutions, Kitchen Planning, Kitchen Equipment, Interiors
        & Civil Work, and Food Packaging Solutions. Manago stands for a personal
        Manager for each industry owner to take control and remove dependency on
        staff. Industry owners benefit from getting all required services under
        one umbrella, optimising operations and easy access to all daily need
        services.
      </p>
      <h2 className="text-3xl font-medium pb-4">Our Services</h2>
      <ul>
        <li className="pb-4">Manago Manpower</li>
        <p className="pb-4">
          We provide all kinds of staff for the Food & Beverages Industry, from
          Kitchen Helpers to Executive Chefs and from Runners to Managers on the
          Floor. We also conduct Background Criminal and Aadhaar checks of
          candidates for the safety of our clients.
        </p>
      </ul>
      <h2 className="text-3xl font-medium pb-2">
        Interpretation and Definitions
      </h2>
      <h3 className="text-2xl font-medium pb-2">Interpretation</h3>
      <p className="pb-4">
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>
      <h3 className="text-2xl font-medium pb-2">Definitions</h3>
      <p className="pb-4">For the purposes of this Privacy Policy:</p>
      <ul className="list-disc pl-5 pb-4">
        <li>
          <strong>Personal Data:</strong> Personal Data means data about a
          living individual who can be identified from those data (or from those
          and other information either in our possession or likely to come into
          our possession).
        </li>
        <li>
          <strong>Usage Data:</strong> Usage Data is data collected
          automatically either generated by the use of the Service or from the
          Service infrastructure itself (for example, the duration of a page
          visit).
        </li>
        <li>
          <strong>Cookies:</strong> Cookies are small files placed on your
          device (computer, mobile phone, or any other device) by a website,
          containing details of your browsing history on that website among its
          many uses.
        </li>
      </ul>
      <h2 className="text-3xl font-medium pb-2">
        Collecting and Using Your Personal Data
      </h2>
      <h3 className="text-2xl font-medium pb-2">Types of Data Collected</h3>
      <h3 className="text-xl font-medium pb-2">Personal Data</h3>
      <p className="pb-4">
        While using our Service, we may ask you to provide us with certain
        personally identifiable information that can be used to contact or
        identify you ("Personal Data"). Personally identifiable information may
        include, but is not limited to:
      </p>
      <ul className="list-disc pl-5 pb-4">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address</li>
        <li>GST number for company registration</li>
        <li>Aadhaar details for candidates</li>
      </ul>
      <h3 className="text-xl font-medium pb-2">Usage Data</h3>
      <p className="pb-4">
        We may also collect information on how the Service is accessed and used
        ("Usage Data"). This Usage Data may include information such as your
        computer's Internet Protocol address (e.g., IP address), browser type,
        browser version, the pages of our Service that you visit, the time and
        date of your visit, the time spent on those pages, unique device
        identifiers, and other diagnostic data.
      </p>
      <h2 className="text-2xl font-medium pb-2">
        Tracking Technologies and Cookies
      </h2>
      <p className="pb-2">
        We use Cookies and similar tracking technologies to track the activity
        on our Service and hold certain information. Cookies are files with
        small amount of data which may include an anonymous unique identifier.
        Cookies are sent to your browser from a website and stored on your
        device. Tracking technologies also used are beacons, tags, and scripts
        to collect and track information and to improve and analyze our Service.
      </p>
      <p className="pb-4">
        You can instruct your browser to refuse all cookies or to indicate when
        a cookie is being sent. However, if you do not accept cookies, you may
        not be able to use some portions of our Service.
      </p>
      <h3 className="text-2xl font-medium pb-2">Use of Your Personal Data</h3>
      <p className="pb-4">
        Manago Manpower Solutions uses the collected data for various purposes:
      </p>
      <ul className="list-disc pl-5 pb-4">
        <li>To provide and maintain our Service</li>
        <li>To notify you about changes to our Service</li>
        <li>
          To allow you to participate in interactive features of our Service
          when you choose to do so
        </li>
        <li>To provide customer support</li>
        <li>
          To gather analysis or valuable information so that we can improve our
          Service
        </li>
        <li>To monitor the usage of our Service</li>
        <li>To detect, prevent and address technical issues</li>
        <li>
          To issue offer letters and experience letters via the mobile app
        </li>
      </ul>
      <p className="pb-4">
        Manago Manpower Solutions will take all steps reasonably necessary to
        ensure that your data is treated securely and in accordance with this
        Privacy Policy and no transfer of your Personal Data will take place to
        an organization or a country unless there are adequate controls in place
        including the security of your data and other personal information.
      </p>
      <h3 className="text-3xl font-medium pb-2">
        Disclosure of Your Personal Data
      </h3>
      <p className="text-2xl font-medium pb-2">Business Transaction</p>
      <p className="pb-4">
        If Manago Manpower Solutions is involved in a merger, acquisition or
        asset sale, your Personal Data may be transferred. We will provide
        notice before your Personal Data is transferred and becomes subject to a
        different Privacy Policy.
      </p>
      <p className="text-2xl font-medium pb-2">Law Enforcement</p>
      <p className="pb-4">
        Under certain circumstances, Manago Manpower Solutions may be required
        to disclose your Personal Data if required to do so by law or in
        response to valid requests by public authorities (e.g. a court or a
        government agency).
      </p>
      <h3 className="text-2xl font-medium pb-2">
        Security of Your Personal Data
      </h3>
      <p className="pb-4">
        The security of your Personal Data is important to us, but remember that
        no method of transmission over the Internet, or method of electronic
        storage is 100% secure. While we strive to use commercially acceptable
        means to protect your Personal Data, we cannot guarantee its absolute
        security.
      </p>
      <h3 className="text-2xl font-medium pb-2">Service Providers</h3>
      <p className="pb-2">
        We may employ third party companies and individuals to facilitate our
        Service ("Service Providers"), provide the Service on our behalf,
        perform Service-related services or assist us in analyzing how our
        Service is used.
      </p>
      <p className="pb-4">
        These third parties have access to your Personal Data only to perform
        these tasks on our behalf and are obligated not to disclose or use it
        for any other purpose.
      </p>
      <h3 className="text-2xl font-medium pb-2">Links to Other Sites</h3>
      <p className="pb-2">
        Our Service may contain links to other sites that are not operated by
        us. If you click on a third party link, you will be directed to that
        third party's site. We strongly advise you to review the Privacy Policy
        of every site you visit.
      </p>
      <p className="pb-4">
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.
      </p>
      <h3 className="text-2xl font-medium pb-2">
        Changes to This Privacy Policy
      </h3>
      <p className="pb-2">
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on this page.
      </p>
      <p className="pb-4">
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </p>
      <h2 className="text-3xl font-medium pb-4">Cookie Policy</h2>
      <p className="pb-2">
        This Cookies Policy explains what cookies are and how we use them. You
        should read this policy to understand the types of cookies we use, the
        information we collect using cookies, and how that information is used.
        Cookies do not typically contain any information that personally
        identifies a user, but personal information that we store about you may
        be linked to the information stored in and obtained from cookies. For
        further information on how we use, store, and keep your personal data
        secure, see our Privacy Policy.
      </p>
      <p className="pb-4">
        We do not store sensitive personal information, such as mailing
        addresses or account passwords, in the cookies we use.
      </p>
      {/* ------------------------------------------- */}
      <h2 className="text-3xl font-medium pb-2">
        Interpretation and Definitions
      </h2>
      <h3 className="text-2xl font-medium pb-2">Interpretation</h3>
      <p className="pb-4">
        The words with initial letters capitalized have meanings defined under
        the following conditions. The following definitions shall have the same
        meaning regardless of whether they appear in singular or in plural.
      </p>
      <h3 className="text-2xl font-medium pb-2">Definitions</h3>
      <p className="pb-4">For the purposes of this Cookies Policy:</p>
      <ul className="list-disc pl-5 pb-4">
        <li>
          Company (referred to as either "the Company", "We", "Us" or "Our" in
          this Cookies Policy) refers to Manago Manpower Solutions, Manipal
          County Road, #56, 3rd Cross, Aishwarya Crystal Layout, Singasandra,
          Bengaluru, Karnataka 560068.
        </li>
        <li>
          Cookies means small files that are placed on your computer, mobile
          device, or any other device by a website, containing details of your
          browsing history on that website among its many uses.
        </li>
        <li>
          Website refers to Manago Manpower Solutions, accessible from
          https://manago.in
        </li>
        <li>
          You means the individual accessing or using the Website, or a company,
          or any legal entity on behalf of which such individual is accessing or
          using the Website, as applicable.
        </li>
      </ul>
      <h2 className="text-3xl font-medium pb-2">The Use of Cookies</h2>
      <p className="pb-4">We use Cookies to:</p>
      <ul className="list-disc pl-5 pb-4">
        <li>Enhance the functionality of our mobile app</li>
        <li>Provide you with a personalized experience</li>
        <li>Track the performance of our app and improve our services</li>
      </ul>

      <h2 className="text-2xl font-medium pb-2">Type of Cookies We Use</h2>
      <p className="pb-4">
        Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies
        remain on your personal computer or mobile device when you go offline,
        while Session Cookies are deleted as soon as you close your web browser.
      </p>
      <ul className="list-decimal pl-5 pb-4">
        <li>
          <strong className='text-lg'>Essential Cookies</strong>
          <ul className="list-disc pl-5 pb-4">
            <li>Type: Session Cookies</li>
            <li>Administered by: Us</li>
            <li>
              Purpose: These cookies are essential to provide you with services
              available through our website and to enable you to use its
              features. They help to authenticate users and prevent fraudulent
              use of user accounts. Without these cookies, the services that you
              have asked for cannot be provided.
            </li>
          </ul>
        </li>
        <li>
          <strong className='text-lg'>Functionality Cookies</strong>
          <ul className="list-disc pl-5 pb-4">
            <li>Type: Persistent Cookies</li>
            <li>Administered by: Us</li>
            <li>
              Purpose: These cookies allow us to remember choices you make when
              you use our website, such as remembering your login details or
              language preference. The purpose of these cookies is to provide
              you with a more personalized experience and to avoid you having to
              re-enter your preferences every time you visit the website.
            </li>
          </ul>
        </li>
      </ul>
      <h2 className="text-3xl font-medium pb-2">
        Your Choices Regarding Cookies
      </h2>
      <h3 className="text-2xl font-medium pb-2">
        Managing Cookies in Your Browser
      </h3>
      <p className="pb-4">
        If you prefer to avoid the use of cookies on our website, you must first
        disable the use of cookies in your browser and then delete the cookies
        saved in your browser associated with this website. You can do this at
        any time.
      </p>
      <p className="pb-4">
        You can control and manage Cookies in various ways:
      </p>
      <ul className="list-disc pl-5 pb-4">
        <li>
          <strong>Browser Settings:</strong> You can set your browser to refuse all or some
          Cookies or to alert you when websites set or access Cookies. If you
          disable or refuse Cookies, please note that some parts of the app may
          become inaccessible or not function properly.
        </li>
        <li>
        <strong> Mobile Device Settings:</strong> You can manage Cookies through your mobile
          device settings. Instructions for managing Cookies can usually be
          found in the device's settings menu.
        </li>
      </ul>
      <p className="pb-4">
        Please note: If you do not accept our cookies, you may experience some
        inconvenience in your use of the website, and some features may not
        function properly.
      </p>

      <h2 className="text-2xl font-medium pb-2">How to Delete Cookies</h2>
      <p className="pb-4">
        Most web browsers allow you to control cookies through their settings
        preferences. However, if you limit the ability of websites to set
        cookies, you may worsen your overall user experience, since it will no
        longer be personalized to you. It may also stop you from saving
        customized settings like login information.
      </p>



      <h2 className="text-3xl font-medium pb-4">Contact Us</h2>
      <p className="pb-4">
        If you have any questions about this Cookies Policy, please contact us:
      </p>
      <ul className="list-disc pl-5 pb-4">
        <li>By email: info@manago.in</li>
        <li>By phone: 7338000475</li>
        <li>
          By mail: Manago Manpower Solutions, Manipal County Road, #56, 3rd
          Cross, Aishwarya Crystal Layout, Singasandra, Bengaluru, Karnataka
          560068.
        </li>
      </ul>
      // ... existing code ...
    </div>
  );
}
